### ISSUE TITLE
subscription Precondition failed

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#131]
**Describe the bug**
When I send a `subscription` request, I get an error `NIOCore/NIOLoopBound.swift:120: Precondition failed`
I make request in `apollo sandbox` in `safari` browser, if I make request in `firefox` I get error `Unable to reach subscription server` in `apollo sandbox`without the error `NIOCore/NIOLoopBound.swift:120: Precondition failed`.
I get the same behavior in the [example](https://github.com/d-exclaimation/pioneer-example)

**To Reproduce**
1. In your browser, go to http://localhost:8080/graphql
2. Make a request: 
```gql
subscription Subscription($to: ID!) {
  listen(to: $to) {
    id
  }
}
```
with variables 
```gql
{
  "to": "some id"
}
```

**Expected behavior**
Apollo sandbox should have signed up for updates.

**Screenshots**
Request made from Firefox browser
<img width="398" alt="Bildschirmfoto 2023-06-13 um 15 20 18" src="https://github.com/d-exclaimation/pioneer/assets/50185064/c0678084-e02c-4cde-957f-3480367cb643">
<img width="1122" alt="Bildschirmfoto 2023-06-13 um 15 20 47" src="https://github.com/d-exclaimation/pioneer/assets/50185064/2828a9ab-81a5-4be8-8e0f-c1239fbc04f1">

Request made from the Safari browser
<img width="1512" alt="Bildschirmfoto 2023-06-13 um 15 21 17" src="https://github.com/d-exclaimation/pioneer/assets/50185064/c484a83b-28b9-4b61-bcb7-a42f3730027b">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.4 (22F66)
 - Pioneer configuration:
 My settings
```swift
Pioneer(
        schema: schema,
        resolver: GraphQLResolver(app: app),
        httpStrategy: .csrfPrevention,
        websocketProtocol: .graphqlWs,
        introspection: true,
        playground: .sandbox,
        validationRules: .computed { gql in
            [depthLimit(gql.ast, max: 10)]
        }
    )
```
Settings from the example
```swift
Pioneer(
    schema: schema(), 
    resolver: .init(), 
    httpStrategy: .csrfPrevention, 
    websocketProtocol: .graphqlWs, 
    introspection: true, 
    playground: .sandbox,
    validationRules: .computed({ gql in 
        [depthLimit(gql.ast, max: 10)]
    })
)
```
**Additional context**
In `apollo sandbox` I use the following settings
<img width="583" alt="Bildschirmfoto 2023-06-13 um 15 27 43" src="https://github.com/d-exclaimation/pioneer/assets/50185064/09e6abf7-1034-45de-8530-c366cf18eb97">

**Comment by d-exclaimation** [comment]
I'll look into it, thanks for reporting

**Comment by d-exclaimation** [comment]
It worked fine on Chrome, but I did check that it does fails on Safari and Firefox. I think I narrowed it down to the fact non-Chromium browser doesn't like it when a single path / endpoint is used for http and websocket. I'll made an update where you have provide a separate WebSocket endpoint

**Comment by d-exclaimation** [comment]
I think `v1.2.2` fixes the issue, and WebSocket should work now in Firefox and Safari. 

Although, if connecting to WebSocket using the same path for HTTP poses a problem, there's now the `"/graphql/websocket"` endpoint that only handles WebSocket and should be more consistent.

Let me know if the precondition failure happen again, I have not been able to reproduce that exact error message.

**Comment by ZirgVoice** [comment]
In Firefox and Safari now works. But Precondition failed error is still there, tried to run through the console, there is the same error.
<img width="1122" alt="Bildschirmfoto 2023-06-14 um 10 12 29" src="https://github.com/d-exclaimation/pioneer/assets/50185064/7f1cb6dd-c625-4288-a5be-aa9d81140661">

**Comment by ZirgVoice** [comment]
`Websocket-kit` version `2.11.0` has no `Precondition failed` error, but no connection,` apollo sandbox` gives error `Unable to reach subscription server`

**Comment by d-exclaimation** [comment]
What version of `websocket-kit` were you using before that gives the precondition errors?

**Comment by ZirgVoice** [comment]
From version `2.12.0` the error `Precondition failed`

**Comment by d-exclaimation** [comment]
I see, I haven't checked if Pioneer is working perfectly with the latest version of Vapor (and subsequently WebsocketKit). I assumed nothing should be breaking since it's not a major update.

**Comment by ZirgVoice** [comment]
The error occurs [here](https://github.com/vapor/websocket-kit/blob/53fe0639a98903858d0196b699720decb42aee7b/Sources/WebSocketKit/WebSocket.swift#L62), and just in 2.12.0 they changed

```swift
    public func onText(_ callback: @escaping (WebSocket, String) -> () {
        self.onTextCallback = callback
    }
```
at 
```swift
   @preconcurrency public func onText(_ callback: @Sendable @escaping (WebSocket, String) -> ()) {
        self.onTextCallback.value = callback
    }
```

**Comment by d-exclaimation** [comment]
Cheers, I'll update the dependencies version Pioneer is using and fix the usage of that funciton

**Comment by d-exclaimation** [comment]
yep current usage of the onText callback would fail because it is called from a Task

**Comment by d-exclaimation** [comment]
Alright, I think `v1.3.0` should resolve this issue. I bumped up all versions of dependencies for this library to their latest non-major. Unfortunately, I also have to drop support for Swift 5.5 since SwiftNIO and Vapor did the same

**Comment by d-exclaimation** [comment]
Feel free to re-open this issue, if the problem still persist
